### ISSUE TITLE
install fails during "RETRYING: Verify that TSB is running"

### ISSUE THREAD

**Issue by robdaems** [gshipley/installcentos#17] opened 2018-03-07 12:52 UTC
OS: `Linux centos 3.10.0-693.17.1.el7.x86_64 #1 SMP Thu Jan 25 20:13:58 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

Exports which are required by the installation step:
```
PASSWORD=rob
USERNAME=rob
DISK=/dev/sda
DOMAIN=192.168.0.135.nip.io
```

After starting following script:
`curl https://raw.githubusercontent.com/gshipley/installcentos/master/install-openshift.sh | /bin/bash`
which calls
`ansible-playbook -i inventory.ini openshift-ansible/playbooks/byo/config.yml`

The ansible playbook failed with following error:
```
...
TASK [template_service_broker : Verify that TSB is running] ********************
FAILED - RETRYING: Verify that TSB is running (120 retries left).
FAILED - RETRYING: Verify that TSB is running (119 retries left).
FAILED - RETRYING: Verify that TSB is running (118 retries left).
...
FAILED - RETRYING: Verify that TSB is running (2 retries left).
FAILED - RETRYING: Verify that TSB is running (1 retries left).
fatal: [192.168.0.135]: FAILED! => {"attempts": 120, "changed": false, "cmd": ["curl", "-k", "https://apiserver.openshift-template-service-broker.svc/healthz"], "delta": "0:00:01.066711", "end": "2018-03-07 13:44:18.024722", "msg": "non-zero return code", "rc": 7, "start": "2018-03-07 13:44:16.958011", "stderr": "  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed connect to apiserver.openshift-template-service-broker.svc:443; Connection refused", "stderr_lines": ["  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current", "                                 Dload  Upload   Total   Spent    Left  Speed", "", "  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed connect to apiserver.openshift-template-service-broker.svc:443; Connection refused"], "stdout": "", "stdout_lines": []}
        to retry, use: --limit @/root/openshift-ansible/playbooks/byo/config.retry

PLAY RECAP *********************************************************************
192.168.0.135              : ok=981  changed=351  unreachable=0    failed=1
localhost                  : ok=13   changed=0    unreachable=0    failed=0


INSTALLER STATUS ***************************************************************
Initialization             : Complete
Health Check               : Complete
etcd Install               : Complete
Master Install             : Complete
Master Additional Install  : Complete
Node Install               : Complete
Hosted Install             : Complete
Metrics Install            : Complete
Logging Install            : Complete
Service Catalog Install    : In Progress
        This phase can be restarted by running: playbooks/byo/openshift-cluster/service-catalog.yml



Failure summary:


  1. Hosts:    192.168.0.135
     Play:     Service Catalog
     Task:     Verify that TSB is running
     Message:  non-zero return code
Adding password for user rob
cluster role "cluster-admin" added: "rob"
******
* Your conosle is https://console.192.168.0.135.nip.io:8443
* Your username is rob
* Your password is rob
*
* Login using:
*
$ oc login -u rob -p rob https://console.192.168.0.135.nip.io:8443/
******
error: dial tcp 192.168.0.135:8443: getsockopt: connection refused - verify you have provided the correct host and port and that the server is currently running.
[root@centos ~]#
```

**Comment by slaterx** [comment] 2018-03-12 05:19
Looks like this is the root cause: https://bugzilla.redhat.com/show_bug.cgi?id=1538616

**Comment by marekjelen** [comment] 2018-04-12 10:30
Several patches were merged, could not reproduce today when running clean installation. Closing the issue, please reopen in case the problem persists and let's figure out what the root cause is.

**Closed by marekjelen** 2018-04-12 10:30 UTC
